brands/urls.py
from django.urls import path

from .views import (BrandCreateView, BrandDeleteView, BrandListView,
                    BrandUpdateView)

app_name = "brands"
urlpatterns = [
    path("list/", BrandListView.as_view(), name="list"),
    path("create/", BrandCreateView.as_view(), name="create"),
    path("update/<slug:slug>/", BrandUpdateView.as_view(), name="update"),
    path("delete/<slug:slug>/", BrandDeleteView.as_view(), name="delete"),
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("account/", include("accounts.urls", namespace="account")),
    path("profile/", include("profiles.urls", namespace="profile")),
    path("products/", include("products.urls", namespace="products")),
    path("brands/", include("brands.urls", namespace="brands")),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

brands/models.py
from django.db import models
from django.utils.text import slugify

from helpers import get_file_path


# Create your models here.
class Brand(models.Model):
    name = models.CharField(max_length=125)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=get_file_path)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Brand, self).save(*args, **kwargs)

brands/views.py
from braces.views import StaffuserRequiredMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, View

from .models import Brand


# Create your views here.
class BrandListView(StaffuserRequiredMixin, ListView):
    model = Brand
    template_name = "brands/list.html"
    context_object_name = "brand_list"


class BrandCreateView(StaffuserRequiredMixin, SuccessMessageMixin, CreateView):
    model = Brand
    fields = ("name", "image")
    success_url = reverse_lazy("brands:list")
    success_message = "brand created successfully"
    template_name = "brands/create.html"


class BrandUpdateView(StaffuserRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Brand
    fields = ("name", "image")
    success_url = reverse_lazy("brands:list")
    success_message = "brand updated successfully"
    template_name = "brands/update.html"


class BrandDeleteView(StaffuserRequiredMixin, View):
    def get(self, *args, **kwargs):
        brand = get_object_or_404(Brand, slug=kwargs.get("slug"))
        brand.delete()
        messages.success(self.request, "brand deleted successfully", "success")
        return redirect("brands:list")

brands/templates/brands/create.html
{% extends "panel/base.html" %}
{% load widget_tweaks %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-full">
            <div class="content-header">
                <div class="d-flex align-items-center">
                    <div class="mr-auto">
                        <h3 class="page-title text-success">Brand Create</h3>
                    </div>
                </div>
            </div>
            <section class="content">
                <div class="row">
                    <div class="col-12">
                        <div class="box">
                            <div class="box-header with-border">
                                <h4 class="box-title text-success">Brand Form</h4>
                            </div>
                            <div class="box-body">
                                <form method="post" action="" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {% for field in form.visible_fields %}
                                        <label class="col-form-label col-md-2">{{ field.label }}</label>
                                        {{ field|add_class:'form-control' }}
                                        {% for error in field.errors %}
                                            <span class="help-block">{{ error }}</span>
                                        {% endfor %}
                                    {% endfor %}
                                    <br>
                                    <br>
                                    <button type="submit" class="form-control btn btn-success">
                                        Add New Brand
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
            </section>
        </div>
    </div>
{% endblock content %}

brands/templates/brands/list.html
{% extends 'panel/base.html' %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-full">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="d-flex align-items-center">
                    <div class="mr-auto">
                        <h3 class="page-title">Brand List</h3>
                        <div class="d-inline-block align-items-center">
                            <nav>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item active" aria-current="page">
                                        <a class="btn btn-success" href="{% url 'brands:create' %}"><h3>Add New
                                            Brand</h3></a></li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Main content -->
            <section class="content">

                <div class="row">


                    <div class="col-12">
                        <div class="box">
                            <div class="box-header with-border">
                                <h4 class="box-title">Brand List</h4>
                                <div class="box-controls pull-right">
                                    <div class="lookup lookup-circle lookup-right">
                                        <input type="text" name="s">
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body no-padding">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <tr>
                                            <th>#</th>
                                            <th>image</th>
                                            <th>name</th>
                                            <th>product count</th>
                                            <th>update</th>
                                            <th>delete</th>
                                        </tr>
                                        {% for brand in brand_list %}
                                            <tr>
                                                <td>{{ forloop.counter }}</td>
                                                <td><img src="{{ brand.image.url }}"></td>
                                                <td>{{ brand.name }}</td>
                                                <td>{{ product.name }}</td>
                                                <td><a class="btn btn-warning"
                                                       href="{% url "brands:update" brand.slug %}">Update
                                                </a>
                                                </td>
                                                <td><a class="btn btn-danger"
                                                       href="{% url "brands:delete" brand.slug %}">Delete
                                                </a>
                                                </td>
                                            </tr>
                                        {% empty %}
                                            <h1>No Brands Added Net</h1>
                                        {% endfor %}

                                    </table>
                                </div>
                            </div>
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box -->
                    </div>


                </div>
                <!-- /.row -->

            </section>
            <!-- /.content -->
        </div>
    </div>
{% endblock %}

brands/templates/brands/update.html
{% extends "panel/base.html" %}
{% load widget_tweaks %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-full">
            <div class="content-header">
                <div class="d-flex align-items-center">
                    <div class="mr-auto">
                        <h3 class="page-title text-warning">Brand Update {{ Brand }}</h3>
                    </div>
                </div>
            </div>
            <section class="content">
                <div class="row">
                    <div class="col-12">
                        <div class="box">
                            <div class="box-header with-border">
                                <h4 class="box-title text-warning">Brand Form</h4>
                            </div>
                            <div class="box-body">
                                <form method="post" action="" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {% for field in form.visible_fields %}
                                        <label class="col-form-label col-md-2">{{ field.label }}</label>
                                        {{ field|add_class:'form-control' }}
                                        {% for error in field.errors %}
                                            <span class="help-block">{{ error }}</span>
                                        {% endfor %}
                                    {% endfor %}
                                    <br>
                                    <br>
                                    <button type="submit" class="form-control btn btn-warning">
                                        Update Brand
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
            </section>
        </div>
    </div>
{% endblock content %}