accounts/urls.py
from django.urls import path

from .views import (AdminUserCreateView, AdminUserListView, UserAuthView,
                    UserDashboardView, UserDeleteView, UserListView,
                    UserLogoutView, UserVerifyView)

app_name = "account"
urlpatterns = [
    path("auth/", UserAuthView.as_view(), name="auth"),
    path("verify/", UserVerifyView.as_view(), name="verify"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("dashboard/<int:user_id>/", UserDashboardView.as_view(), name="dashboard"),
    path("admin_list/", AdminUserListView.as_view(), name="admin_list"),
    path("user_list/", UserListView.as_view(), name="user_list"),
    path("admin_create/", AdminUserCreateView.as_view(), name="admin_create"),
    path("delete/<int:user_id>/", UserDeleteView.as_view(), name="delete"),
]

brands/urls.py
from django.urls import path

from .views import (BrandCreateView, BrandDeleteView, BrandListView,
                    BrandUpdateView)

app_name = "brands"
urlpatterns = [
    path("list/", BrandListView.as_view(), name="list"),
    path("create/", BrandCreateView.as_view(), name="create"),
    path("update/<slug:slug>/", BrandUpdateView.as_view(), name="update"),
    path("delete/<slug:slug>/", BrandDeleteView.as_view(), name="delete"),
]

products/urls.py
from django.urls import path

from .views import (ProductAdminDetailView, ProductCreateView,
                    ProductDeleteView, ProductDetailView, ProductListView,
                    ProductsListAdmin, ProductUpdateView)

app_name = "products"
urlpatterns = [
    path("list_admin/", ProductsListAdmin.as_view(), name="list_admin"),
    path("list/", ProductListView.as_view(), name="list"),
    path("admin/<slug:slug>/", ProductAdminDetailView.as_view(), name="detail_admin"),
    path("create/", ProductCreateView.as_view(), name="create"),
    path("update/<slug:slug>/", ProductUpdateView.as_view(), name="update"),
    path("delete/<slug:slug>/", ProductDeleteView.as_view(), name="delete"),
    path("<slug:slug>/", ProductDetailView.as_view(), name="detail"),
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("account/", include("accounts.urls", namespace="account")),
    path("profile/", include("profiles.urls", namespace="profile")),
    path("products/", include("products.urls", namespace="products")),
    path("brands/", include("brands.urls", namespace="brands")),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

templates/panel/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../images/favicon.ico">

    <title>پنل مدیریتی سانی ادمین</title>

    <!-- Vendors Style-->
    <link rel="stylesheet" href="{% static 'panel/css/vendors_css.css' %}">

    <!-- Style-->
    <link rel="stylesheet" href="{% static 'panel/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'panel/css/skin_color.css' %}">

</head>

<body class="hold-transition light-skin sidebar-mini theme-primary fixed">

<div class="wrapper">

    {#    <header class="main-header">#}
    {#        <!-- Header Navbar -->#}
    {#        <nav class="navbar navbar-static-top pl-30">#}
    {#            <!-- Sidebar toggle button-->#}
    {#            <div>#}
    {#                <ul class="nav">#}
    {#                    <li class="btn-group nav-item">#}
    {#                        <a href="#" class="waves-effect waves-light nav-link rounded svg-bt-icon"#}
    {#                           data-toggle="push-menu" role="button">#}
    {#                            <i class="nav-link-icon mdi mdi-menu"></i>#}
    {#                        </a>#}
    {#                    </li>#}
    {#                    <li class="btn-group nav-item">#}
    {#                        <a href="#" data-provide="fullscreen"#}
    {#                           class="waves-effect waves-light nav-link rounded svg-bt-icon" title="تمام صفحه">#}
    {#                            <i class="nav-link-icon mdi mdi-crop-free"></i>#}
    {#                        </a>#}
    {#                    </li>#}
    {#                    <li class="btn-group nav-item d-none d-xl-inline-block">#}
    {#                        <a href="#" class="waves-effect waves-light nav-link rounded svg-bt-icon" title="">#}
    {#                            <i class="ti-check-box"></i>#}
    {#                        </a>#}
    {#                    </li>#}
    {#                    <li class="btn-group nav-item d-none d-xl-inline-block">#}
    {#                        <a href="calendar.html" class="waves-effect waves-light nav-link rounded svg-bt-icon" title="">#}
    {#                            <i class="ti-calendar"></i>#}
    {#                        </a>#}
    {#                    </li>#}
    {#                </ul>#}
    {#            </div>#}
    {##}
    {#            <div class="navbar-custom-menu r-side">#}
    {#                <ul class="nav navbar-nav">#}
    {#                    <!-- full Screen -->#}
    {#                    <li class="search-bar">#}
    {#                        <div class="lookup lookup-circle lookup-right">#}
    {#                            <input type="text" name="s">#}
    {#                        </div>#}
    {#                    </li>#}
    {#                    <!-- Notifications -->#}
    {#                    <li class="dropdown notifications-menu">#}
    {#                        <a href="#" class="waves-effect waves-light rounded dropdown-toggle" data-toggle="dropdown"#}
    {#                           title="اعلان ها">#}
    {#                            <i class="ti-bell"></i>#}
    {#                        </a>#}
    {#                        <ul class="dropdown-menu animated bounceIn">#}
    {##}
    {#                            <li class="header">#}
    {#                                <div class="p-20">#}
    {#                                    <div class="flexbox">#}
    {#                                        <div>#}
    {#                                            <h4 class="mb-0 mt-0">اعلان ها</h4>#}
    {#                                        </div>#}
    {#                                        <div>#}
    {#                                            <a href="#" class="text-danger">پاک کردن همه</a>#}
    {#                                        </div>#}
    {#                                    </div>#}
    {#                                </div>#}
    {#                            </li>#}
    {##}
    {#                            <li>#}
    {#                                <!-- inner menu: contains the actual data -->#}
    {#                                <ul class="menu sm-scrol">#}
    {#                                    <li>#}
    {#                                        <a href="#">#}
    {#                                            <i class="fa fa-users text-info"></i> لورم ایپسوم متن ساختگی با تولید سادگی#}
    {#                                        </a>#}
    {#                                    </li>#}
    {#                                    <li>#}
    {#                                        <a href="#">#}
    {#                                            <i class="fa fa-warning text-warning"></i> متن ساختگی صنعت چاپ با تولید#}
    {#                                            سادگی#}
    {#                                        </a>#}
    {#                                    </li>#}
    {#                                    <li>#}
    {#                                        <a href="#">#}
    {#                                            <i class="fa fa-users text-danger"></i> تولید سادگی نامفهوم با متن ساختگی#}
    {#                                            لورم ایپسوم در صنعت چاپ#}
    {#                                        </a>#}
    {#                                    </li>#}
    {#                                    <li>#}
    {#                                        <a href="#">#}
    {#                                            <i class="fa fa-shopping-cart text-success"></i> لورم ایپسوم با تولید سادگی#}
    {#                                            نامفهوم#}
    {#                                        </a>#}
    {#                                    </li>#}
    {#                                    <li>#}
    {#                                        <a href="#">#}
    {#                                            <i class="fa fa-user text-danger"></i> متن ساختگی با تولید سادگی نامفهوم در#}
    {#                                            صنعت چاپ#}
    {#                                        </a>#}
    {#                                    </li>#}
    {#                                    <li>#}
    {#                                        <a href="#">#}
    {#                                            <i class="fa fa-user text-primary"></i> لورم ایپسوم متن ساختگی#}
    {#                                        </a>#}
    {#                                    </li>#}
    {#                                    <li>#}
    {#                                        <a href="#">#}
    {#                                            <i class="fa fa-user text-success"></i> با تولید سادگی نامفهوم در صنعت چاپ#}
    {#                                            متن ساختگی#}
    {#                                        </a>#}
    {#                                    </li>#}
    {#                                </ul>#}
    {#                            </li>#}
    {#                            <li class="footer">#}
    {#                                <a href="#">مشاهده همه</a>#}
    {#                            </li>#}
    {#                        </ul>#}
    {#                    </li>#}
    {##}
    {#                    <!-- User Account-->#}
    {#                    <li class="dropdown user user-menu">#}
    {#                        <a href="#" class="waves-effect waves-light rounded dropdown-toggle p-0" data-toggle="dropdown"#}
    {#                           title="کاربر">#}
    {#                            <img src="../images/avatar/1.jpg" alt="">#}
    {#                        </a>#}
    {#                        <ul class="dropdown-menu animated flipInX">#}
    {#                            <li class="user-body">#}
    {#                                <a class="dropdown-item" href="#"><i class="ti-user text-muted mr-2"></i> پروفایل</a>#}
    {#                                <a class="dropdown-item" href="#"><i class="ti-wallet text-muted mr-2"></i> کیف پول#}
    {#                                    من</a>#}
    {#                                <a class="dropdown-item" href="#"><i class="ti-settings text-muted mr-2"></i>#}
    {#                                    تنظیمات</a>#}
    {#                                <div class="dropdown-divider"></div>#}
    {#                                <a class="dropdown-item" href="#"><i class="ti-lock text-muted mr-2"></i> خروج</a>#}
    {#                            </li>#}
    {#                        </ul>#}
    {#                    </li>#}
    {#                    <li>#}
    {#                        <a href="#" data-toggle="control-sidebar" title="تنظیمات" class="waves-effect waves-light">#}
    {#                            <i class="ti-settings"></i>#}
    {#                        </a>#}
    {#                    </li>#}
    {##}
    {#                </ul>#}
    {#            </div>#}
    {#        </nav>#}
    {#    </header>#}


    {% include 'panel/navbar.html' %}


    {% block content %}
    {% endblock %}
    <footer class="main-footer">

        &copy; all right reserved
    </footer>


    <!-- Add the sidebar's background. This div must be placed immediately after the control sidebar -->
    <div class="control-sidebar-bg"></div>

</div>
<!-- ./wrapper -->


<!-- Vendor JS -->
<script src="{% static 'panel/js/vendors.min.js' %}"></script>
<script src="{% static 'panel/icons/feather-icons/feather.min.js' %}"></script>
<script src="{% static 'panel/vendor_components/easypiechart/dist/jquery.easypiechart.js' %}"></script>
<script src="{% static 'panel/vendor_components/apexcharts-bundle/irregular-data-series.js' %}"></script>
<script src="{% static 'panel/vendor_components/apexcharts-bundle/dist/apexcharts.js' %}"></script>

<!-- Sunny Admin App -->
<script src="{% static 'panel/js/template.js' %}"></script>
<script src="{% static 'panel/js/pages/dashboard.js{%static ' %}"></script>


</body>
</html>

templates/panel/navbar.html
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar-->
    <section class="sidebar">

        <div class="user-profile">
            <div class="ulogo">
                <a href="index.html">
                    <!-- logo for regular state and mobile devices -->
                    <div class="d-flex align-items-center justify-content-center">
                        <img src="../images/logo-dark.png" alt="">
                        <h3><b>Sunny</b> Admin</h3>
                    </div>
                </a>
            </div>
        </div>

        <!-- sidebar menu-->
        <ul class="sidebar-menu" data-widget="tree">

            <li>
                <a href="index.html">
                    <i data-feather="pie-chart"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <li class="treeview">
                <a href="#">
                    <i data-feather="message-circle"></i>
                    <span>Products</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-right pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{% url "products:create" %}"><i class="ti-more"></i>Add Products</a></li>
                    <li><a href="{% url "products:list_admin" %}"><i class="ti-more"></i>Products List</a></li>
                </ul>
            </li>


            <li class="treeview">
                <a href="#">
                    <i data-feather="file"></i>
                    <span>Brand</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-right pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{% url "brands:list" %}"><i class="ti-more"></i>Brand List</a></li>
                    <li><a href="{% url "brands:create" %}"><i class="ti-more"></i>Add New Brand</a></li>
                </ul>
            </li>

            <li>
                <a href="index.html">
                    <i data-feather="pie-chart"></i>
                    <span>Useres</span>
                </a>
            </li>

            <li class="treeview">
                <a href="#">
                    <i data-feather="grid"></i>
                    <span>Admin</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-right pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{% url "account:admin_create" %}"><i class="ti-more"></i>Add New Admin</a></li>
                    <li><a href="{% url "account:admin_list" %}"><i class="ti-more"></i>Admin List</a></li>
                </ul>
            </li>


        </ul>
    </section>

    <div class="sidebar-footer">
        <!-- item-->
        <a href="javascript:void(0)" class="link" data-toggle="tooltip" title="" data-original-title="تنظیمات"
           aria-describedby="tooltip92529"><i class="ti-settings"></i></a>
        <!-- item-->
        <a href="mailbox_inbox.html" class="link" data-toggle="tooltip" title="" data-original-title="ایمیل"><i
                class="ti-email"></i></a>
        <!-- item-->
        <a href="{% url "account:logout" %}" class="link" data-toggle="tooltip" title="" data-original-title="Exite"><i
                class="ti-lock"></i></a>
    </div>
</aside>