accounts/urls.py
from django.urls import path

from .views import (AdminUserCreateView, AdminUserListView, UserAuthView,
                    UserDashboardView, UserDeleteView, UserListView,
                    UserLogoutView, UserVerifyView)

app_name = "account"
urlpatterns = [
    path("auth/", UserAuthView.as_view(), name="auth"),
    path("verify/", UserVerifyView.as_view(), name="verify"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("dashboard/<int:user_id>/", UserDashboardView.as_view(), name="dashboard"),
    path("admin_list/", AdminUserListView.as_view(), name="admin_list"),
    path("user_list/", UserListView.as_view(), name="user_list"),
    path("admin_create/", AdminUserCreateView.as_view(), name="admin_create"),
    path("delete/<int:user_id>/", UserDeleteView.as_view(), name="delete"),
]

brands/urls.py
from django.urls import path

from .views import (BrandCreateView, BrandDeleteView, BrandListView,
                    BrandUpdateView)

app_name = "brands"
urlpatterns = [
    path("list/", BrandListView.as_view(), name="list"),
    path("create/", BrandCreateView.as_view(), name="create"),
    path("update/<slug:slug>/", BrandUpdateView.as_view(), name="update"),
    path("delete/<slug:slug>/", BrandDeleteView.as_view(), name="delete"),
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("account/", include("accounts.urls", namespace="account")),
    path("profile/", include("profiles.urls", namespace="profile")),
    path("products/", include("products.urls", namespace="products")),
    path("brands/", include("brands.urls", namespace="brands")),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.core.validators import RegexValidator
from django.db import models

from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    phone_number = models.CharField(
        max_length=11,
        validators=[RegexValidator(r"^09[0|1|2|9][0-9]{8}$")],
        unique=True,
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    USERNAME_FIELD = "phone_number"

    objects = UserManager()

    def __str__(self):
        return self.phone_number

    @property
    def is_staff(self):
        return self.is_admin


class OtpCode(models.Model):
    phone_number = models.CharField(max_length=11)
    code = models.CharField(max_length=6)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.code} at {self.created} to {self.phone_number}"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.validators import ValidationError

from .models import User


class UserCreateForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("phone_number",)

    def clean(self):
        clean_data = super(UserCreateForm, self).clean()
        password = clean_data["password"]
        password_confirm = clean_data["password_confirm"]
        if (password and password_confirm) and (password_confirm != password_confirm):
            raise ValidationError("unmatched password")
        return password

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(
        help_text='you can change password using <a href="../password/">this form</a>.'
    )

    class Meta:
        model = User
        fields = (
            "phone_number",
            "password",
        )


class AuthForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        user_auth = kwargs.pop("user_auth", False)
        super(AuthForm, self).__init__(*args, **kwargs)

        if user_auth:
            self.fields.pop("password")
            self.fields.pop("password_confirm")

    class Meta:
        model = User
        fields = ("phone_number",)


class OtpCodeForm(forms.Form):
    code = forms.CharField(max_length=6)

accounts/views.py
from random import randint

from braces.views import AnonymousRequiredMixin, SuperuserRequiredMixin
from django.contrib import messages
from django.contrib.auth import get_user_model, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView, View

from .forms import AuthForm, OtpCodeForm
from .mixins import AdminMixin
from .models import OtpCode
from .utils import send_otp

user = get_user_model()


class UserAuthView(AnonymousRequiredMixin, FormView):
    template_name = "accounts/auth.html"
    form_class = AuthForm
    success_url = reverse_lazy("account:verify")

    def get_form_kwargs(self):
        kwargs = super(UserAuthView, self).get_form_kwargs()
        kwargs["user_auth"] = True
        return kwargs

    def form_valid(self, form):
        code = randint(000000, 999999)
        phone_number = form.cleaned_data["phone_number"]
        send_otp(phone_number, code)
        OtpCode.objects.create(phone_number=phone_number, code=code)
        self.request.session["user_info"] = {
            "phone_number": form.cleaned_data["phone_number"],
        }
        messages.success(self.request, "code sent", "success")
        return super(UserAuthView, self).form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "error", "danger")
        return super(UserAuthView, self).form_invalid(form)


class UserVerifyView(AnonymousRequiredMixin, FormView):
    template_name = "accounts/verify.html"
    form_class = OtpCodeForm
    authenticated_redirect_url = reverse_lazy("account:dashboard")

    def dispatch(self, request, *args, **kwargs):
        if self.request.META.get("HTTP_REFERER") == "":
            return super(UserVerifyView, self).dispatch(request, *args, **kwargs)
        raise PermissionDenied

    def form_valid(self, form):
        user_session = self.request.session["user_info"]["phone_number"]
        code_instance = OtpCode.objects.get(phone_number=user_session)
        code = form.cleaned_data["code"]
        if code == code_instance:
            code_instance.delete()
            user_obj = user.objects.filter(phone_number=user_session)
            if user_obj.exists():
                login(self.request, user_obj)
            else:
                user.objects.create_user(phone_number=user_session)
            messages.success(self.request, "", "")
        return super(UserVerifyView, self).form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "", "")
        return super(UserVerifyView, self).form_invalid(form)


class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, "", "success")
        return redirect("account:auth")


class UserDashboardView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        print(request.user.id)
        user_obj = get_object_or_404(user, id=user_id)
        return render(request, "accounts/dashboard.html", {"user": user_obj})


class AdminUserListView(SuperuserRequiredMixin, ListView):
    queryset = user.objects.filter(is_admin=True)
    template_name = "accounts/admin_list.html"
    context_object_name = "admin_list"


class UserListView(AdminMixin, ListView):
    queryset = user.objects.exclude(is_admin=True)
    template_name = "accounts/user_list.html"
    context_object_name = "user_list"


class AdminUserCreateView(SuperuserRequiredMixin, FormView):
    redirect_unauthenticated_users = reverse_lazy("account:auth")
    template_name = "accounts/admin_create.html"
    form_class = AuthForm

    def form_valid(self, form):
        cd = form.cleaned_data
        user.objects.create_admin_user(
            phone_number=cd["phone_number"],
            password=cd["password"],
        )
        messages.success(self.request, "", "success")
        return super(AdminUserCreateView, self).form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "", "danger")
        return super(AdminUserCreateView, self).form_invalid(form)


class UserDeleteView(SuperuserRequiredMixin, View):
    def get(self, request, user_id):
        user_obj = get_object_or_404(user, id=user_id)
        user_obj.delete()
        messages.success(request, "", "success")
        return redirect("account:admin_list")

accounts/templates/accounts/admin_create.html
{% extends "panel/base.html" %}
{% load widget_tweaks %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-full">
            <div class="content-header">
                <div class="d-flex align-items-center">
                    <div class="mr-auto">
                        <h3 class="page-title text-success">Admin Create</h3>
                    </div>
                </div>
            </div>
            <section class="content">
                <div class="row">
                    <div class="col-12">
                        <div class="box">
                            <div class="box-header with-border">
                                <h4 class="box-title text-success">Admin Form</h4>
                            </div>
                            <div class="box-body">
                                <form method="post" action="">
                                    {% csrf_token %}
                                    {% for field in form.visible_fields %}
                                        <label class="col-form-label col-md-2">{{ field.label }}</label>
                                        {{ field|add_class:'form-control' }}
                                        {% for error in field.errors %}
                                            <span class="help-block">{{ error }}</span>
                                        {% endfor %}
                                    {% endfor %}
                                    <br>
                                    <br>
                                    <button type="submit" class="form-control btn btn-success">
                                        Add New Admin
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
            </section>
        </div>
    </div>
{% endblock content %}

accounts/templates/accounts/admin_list.html
{% extends 'panel/base.html' %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-full">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="d-flex align-items-center">
                    <div class="mr-auto">
                        <h3 class="page-title">Admin List</h3>
                        <div class="d-inline-block align-items-center">
                            <nav>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item active" aria-current="page">
                                        <a class="btn btn-success" href="{% url 'account:admin_create' %}"><h3>Add New
                                            Admin</h3></a></li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Main content -->
            <section class="content">

                <div class="row">

                    <div class="col-12">
                        <div class="box">
                            <div class="box-header with-border">
                                <h4 class="box-title">Admins</h4>

                            </div>
                            <!-- /.box-header -->
                            <div class="box-body">
                                <div class="table-responsive-sm">
                                    <table class="table mb-0">
                                        <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Phone_Number</th>
                                            <th scope="col">Edite</th>
                                            <th scope="col">Delete</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for admin in admin_list %}
                                            <tr>
                                                <th scope="row">{{ forloop.counter }}</th>
                                                <td>{{ admin.phone_number }}</td>
                                                <td><a class="btn btn-warning"
                                                       href="{% url "account:delete" admin.id %}">Edite {{ admin.phone_number }}</a>
                                                </td>
                                                <td><a class="btn btn-danger"
                                                       href="{% url "account:delete" admin.id %}">Delete {{ admin.phone_number }}</a>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>


                            </div>
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box -->
                    </div>

                    <div class="col-12">
                        <div class="box">
                            <div class="box-header with-border">
                                <h4 class="box-title">جدول ریسپانسیو با هاور</h4>
                                <div class="box-controls pull-right">
                                    <div class="lookup lookup-circle lookup-right">
                                        <input type="text" name="s">
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body no-padding">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <tr>
                                            <th>فاکتور</th>
                                            <th>کاربر</th>
                                            <th>تاریخ</th>
                                            <th>قیمت</th>
                                            <th>وضعیت</th>
                                            <th>کشور</th>
                                        </tr>
                                        <tr>
                                            <td><a href="javascript:void(0)">سفارش #123456</a></td>
                                            <td>لورم ایپسوم</td>
                                            <td><span class="text-muted"><i
                                                    class="fa fa-clock-o"></i> 26 آبان 1399</span></td>
                                            <td>158,000 تومان</td>
                                            <td><span class="badge badge-pill badge-danger">در حال ارسال</span></td>
                                            <td>ایران</td>
                                        </tr>
                                        <tr>
                                            <td><a href="javascript:void(0)">سفارش #458789</a></td>
                                            <td>لورم ایپسوم</td>
                                            <td><span class="text-muted"><i
                                                    class="fa fa-clock-o"></i> 26 آبان 1399</span></td>
                                            <td>55,000 تومان</td>
                                            <td><span class="badge badge-pill badge-warning">ارسال شده</span></td>
                                            <td>ترکیه</td>
                                        </tr>
                                        <tr>
                                            <td><a href="javascript:void(0)">سفارش #84532</a></td>
                                            <td>لورم ایپسوم</td>
                                            <td><span class="text-muted"><i
                                                    class="fa fa-clock-o"></i> 26 آبان 1399</span></td>
                                            <td>845,000 تومان</td>
                                            <td><span class="badge badge-pill badge-danger">در حال بررسی</span></td>
                                            <td>استرالیا</td>
                                        </tr>
                                        <tr>
                                            <td><a href="javascript:void(0)">سفارش #48956</a></td>
                                            <td>لورم ایپسوم</td>
                                            <td><span class="text-muted"><i
                                                    class="fa fa-clock-o"></i> 26 آبان 1399</span></td>
                                            <td>145,000 تومان</td>
                                            <td><span class="badge badge-pill badge-success">پرداخت شده</span></td>
                                            <td>کانادا</td>
                                        </tr>
                                        <tr>
                                            <td><a href="javascript:void(0)">سفارش #92154</a></td>
                                            <td>لورم ایپسوم</td>
                                            <td><span class="text-muted"><i
                                                    class="fa fa-clock-o"></i> 26 آبان 1399</span></td>
                                            <td>450,000 تومان</td>
                                            <td><span class="badge badge-pill badge-warning">ارسال شده</span></td>
                                            <td>چین</td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box -->
                    </div>


                </div>
                <!-- /.row -->

            </section>
            <!-- /.content -->
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/auth.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../images/favicon.ico">

    <title>Auth</title>

    <!-- Vendors Style-->
    <link rel="stylesheet" href="{% static 'panel/css/vendors_css.css' %}">

    <!-- Style-->
    <link rel="stylesheet" href="{% static 'panel/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'panel/css/skin_color.css' %}">

</head>

<body class="hold-transition theme-primary bg-gradient-primary">

<div class="container h-p100">
    <div class="row align-items-center justify-content-md-center h-p100">

        <div class="col-12">
            <div class="row justify-content-center no-gutters">
                <div class="col-lg-4 col-md-5 col-12">
                    <div class="content-top-agile p-10">
                        <h4 class="mb-0 text-white">Enter Your Phone Number</h4>
                    </div>
                    <div class="p-30 rounded30 box-shadowed b-2 b-dashed">
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
											<span class="input-group-text bg-transparent text-white"><i
                                                    class="ti-email"></i></span>
                                    </div>
                                    {% for field in form.visible_fields %}
                                        {{ field|add_class:'form-control pl-15 bg-transparent text-white plc-white' }}
                                        {% for error in field.errors %}
                                            <span class="help-block">{{ error }}</span>
                                        {% endfor %}
                                    {% endfor %}

                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12 text-center">
                                    <button type="submit"
                                            class="btn btn-info btn-rounded margin-top-10">Submit
                                    </button>
                                </div>
                                <!-- /.col -->
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Vendor JS -->
<script src="{% static 'panel/js/vendors.min.js' %}"></script>
<script src="{% static 'panel/icons/feather-icons/feather.min.js' %}"></script>

</body>

</html>

accounts/templates/accounts/dashboard.html
{% extends 'panel/base.html' %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-full">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="d-flex align-items-center">
                    <div class="mr-auto">
                        <h3 class="page-title">dashboard</h3>
                        <div class="d-inline-block align-items-center">
                            <nav>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="index.html"><i
                                            class="mdi mdi-home-outline"></i></a></li>
                                    <li class="breadcrumb-item" aria-current="page">صفحات</li>
                                    <li class="breadcrumb-item active" aria-current="page">پروفایل</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Main content -->
            <section class="content">

                <div class="row">
                    <div class="col-12 col-lg-5 col-xl-4">

                        <div class="box box-inverse bg-img" style="background-image: url(../images/gallery/full/1.jpg);"
                             data-overlay="2">


                            <div class="box-body text-center pb-50">
                                <a href="#">
                                    {#                                    <img class="avatar avatar-xxl avatar-bordered" src="{{ user.profile.image.url }}"#}
                                    {#                                         alt="">#}
                                </a>
                                <h4 class="mt-2 mb-0"><a class="hover-primary text-white"
                                                         href="#">{{ user.phone_number }}</a></h4>
                                <span><i class="fa fa-map-marker w-20"></i> تهران</span>
                            </div>


                        </div>

                        <!-- Profile Image -->
                        <div class="box">
                            <div class="box-body box-profile">
                                <div class="row">
                                    <h3>Personal Info</h3>
                                    <div class="col-12">
                                        <div>
                                            <p>Full_name: <span
                                                    class="text-gray pl-10"></span>
                                            </p>
                                            <p>Phone_number : <span
                                                    class="text-gray pl-10">{{ user.profile.phone_number }}</span></p>
                                            <p>Email : <span class="text-gray pl-10">{{ user.profile.email }}</span></p>
                                            <p>Recive Blog Post : <span
                                                    class="text-gray pl-10">{{ user.profile.receive_blog }}</span></p>
                                        </div>
                                    </div>
                                    <a class="form-control btn btn-warning"
                                       href="{% url "profile:update" user.profile.id %}">update profile</a>

                                </div>
                            </div>
                            <!-- /.box-body -->
                        </div>


                    </div>
                    <div class="col-12 col-lg-7 col-xl-8">

                        <div class="nav-tabs-custom box-profile">
                            <ul class="nav nav-tabs">
                                <li><a class="active" href="#usertimeline" data-toggle="tab">Latest orders</a></li>
                                <li><a href="#activity" data-toggle="tab">Favorite product</a></li>
                                <li><a href="#settings" data-toggle="tab">latest products you have seen</a></li>
                            </ul>

                            <div class="box box-inverse box-carousel slide" data-ride="carousel"
                                 style="background-color: #00aced">
                                <div class="box-header no-border">
                                    <span class="fa fa-twitter font-size-30"></span>
                                    <div class="box-tools pull-right">
                                        <h5 class="box-title box-title-bold"></h5>
                                    </div>
                                </div>

                                <div class="carousel-inner">
                                    <blockquote
                                            class="blockquote blockquote-inverse no-border m-0 py-15 carousel-item active">
                                        <p>به طور کلی ، الزامات پلاگین را برای محصولات قابل تحویل چند منظوره مشخص می
                                            کنید.
                                            یکپارچه عملکرد متقابل را انکوب کنید.</p>
                                        <div class="flexbox">
                                            <time class="text-white" datetime="2017-11-22 20:00">22 آبان 1399</time>
                                            <span><i class="fa fa-heart"></i> 62</span>
                                        </div>
                                    </blockquote>

                                    <blockquote class="blockquote blockquote-inverse no-border m-0 py-15 carousel-item">
                                        <p>انقلابی منحصر به فرد در کاتالیزورهای اهرمی برای تغییر در خدمات وب کلاس جهانی
                                            ایجاد
                                            کرده است. به طور موثر در رقابت.</p>
                                        <div class="flexbox">
                                            <time class="text-white" datetime="2017-11-22 20:00">22 آبان 1399</time>
                                            <span><i class="fa fa-heart"></i> 45</span>
                                        </div>
                                    </blockquote>

                                    <blockquote class="blockquote blockquote-inverse no-border m-0 py-15 carousel-item">
                                        <p>با اشتیاق محصولات تولید شده از میان رسانه ها را بدون خدمات وب پردازش محور
                                            بهینه
                                            کنید.
                                            راحت</p>
                                        <div class="flexbox">
                                            <time class="text-white" datetime="2017-11-22 20:00">22 آبان 1399</time>
                                            <span><i class="fa fa-heart"></i> 65</span>
                                        </div>
                                    </blockquote>
                                </div>

                            </div>                            <!-- /.tab-content -->
                        </div>
                        <!-- /.nav-tabs-custom -->
                    </div>
                </div>
                <!-- /.row -->

            </section>
            <!-- /.content -->
        </div>
    </div>
{% endblock  content%}