products/urls.py
from django.urls import path

from .views import (ProductAdminDetailView, ProductCreateView,
                    ProductDeleteView, ProductDetailView, ProductListView,
                    ProductsListAdmin, ProductUpdateView)

app_name = "products"
urlpatterns = [
    path("list_admin/", ProductsListAdmin.as_view(), name="list_admin"),
    path("list/", ProductListView.as_view(), name="list"),
    path("admin/<slug:slug>/", ProductAdminDetailView.as_view(), name="detail_admin"),
    path("create/", ProductCreateView.as_view(), name="create"),
    path("update/<slug:slug>/", ProductUpdateView.as_view(), name="update"),
    path("delete/<slug:slug>/", ProductDeleteView.as_view(), name="delete"),
    path("<slug:slug>/", ProductDetailView.as_view(), name="detail"),
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("account/", include("accounts.urls", namespace="account")),
    path("profile/", include("profiles.urls", namespace="profile")),
    path("products/", include("products.urls", namespace="products")),
    path("brands/", include("brands.urls", namespace="brands")),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

products/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django_extensions.db.models import TimeStampedModel

from brands.models import Brand
from helpers import get_file_path


# Create your models here.
class Product(TimeStampedModel):
    name = models.CharField(max_length=500)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    screen_size = models.FloatField()
    cpu_cache = models.FloatField()
    ram = models.FloatField()
    memory_capacity = models.FloatField()
    battery_description = models.CharField(max_length=500)
    count = models.PositiveIntegerField()
    image = models.ImageField(upload_to=get_file_path, blank=True)
    price = models.IntegerField()
    brand = models.ForeignKey(
        Brand,
        on_delete=models.CASCADE,
        related_name="products",
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.name

    def save(self, **kwargs):
        self.slug = slugify(self.name)
        return super(Product, self).save()

    def get_absolute_url(self):
        return reverse(
            "products:detail",
            args=[
                self.slug,
            ],
        )

products/forms.py
from django import forms

from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            "name",
            "description",
            "screen_size",
            "cpu_cache",
            "ram",
            "memory_capacity",
            "battery_description",
            "count",
            "image",
            "price",
            "brand",
        ]


class AddToCartForm(forms.Form):
    count = forms.IntegerField(min_value=1)

products/views.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import (CreateView, DetailView, ListView, UpdateView,
                                  View)
from django.views.generic.edit import FormMixin

from accounts.mixins import AdminMixin

from .forms import AddToCartForm, ProductForm
from .models import Product


# products admin views
class ProductsListAdmin(AdminMixin, ListView):
    model = Product
    template_name = "products/product_list_panel.html"
    context_object_name = "product_list"


class ProductAdminDetailView(AdminMixin, DetailView):
    model = Product
    template_name = "products/product_detail_panel.html"
    context_object_name = "product"


class ProductDeleteView(AdminMixin, View):
    def get(self, request, slug):
        product_obj = get_object_or_404(Product, slug=slug)
        product_obj.delete()
        messages.success(request, "", "success")
        return redirect("products:list_admin")


class ProductCreateView(AdminMixin, SuccessMessageMixin, CreateView):
    model = Product
    success_url = reverse_lazy("products:list_admin")
    template_name = "products/create.html"
    SuccessMessageMixin = "created successfully"
    form_class = ProductForm


class ProductUpdateView(AdminMixin, UpdateView):
    model = Product
    template_name = "products/update.html"
    SuccessMessageMixin = "updated successfully"
    form_class = ProductForm
    context_object_name = "product"

    def get_success_url(self):
        return reverse("products:detail_admin", kwargs={"slug": self.object.slug})


class ProductListView(ListView):
    model = Product
    template_name = "products/list.html"
    context_object_name = "product_list"


class ProductDetailView(FormMixin, DetailView):
    model = Product
    template_name = "products/detail.html"
    form_class = AddToCartForm

products/templates/products/create.html
{% extends "panel/base.html" %}
{% load widget_tweaks %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-full">
            <div class="content-header">
                <div class="d-flex align-items-center">
                    <div class="mr-auto">
                        <h3 class="page-title text-success">Product Create</h3>
                    </div>
                </div>
            </div>
            <section class="content">
                <div class="row">
                    <div class="col-12">
                        <div class="box">
                            <div class="box-header with-border">
                                <h4 class="box-title text-success">Product Form</h4>
                            </div>
                            <div class="box-body">
                                <form method="post" action="" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {% for field in form.visible_fields %}
                                        <label class="col-form-label col-md-2">{{ field.label }}</label>
                                        {{ field|add_class:'form-control' }}
                                                                                {% for error in field.errors %}
                                                                                    <span class="help-block">{{ error }}</span>
                                                                                {% endfor %}
                                    {% endfor %}
                                    <br>
                                    <br>
                                    <button type="submit" class="form-control btn btn-success">
                                        Add New Product
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
            </section>
        </div>
    </div>
{% endblock content %}

products/templates/products/detail.html
{% extends 'site/base.html' %}

{% block content %}
    <h2>{{ product.name }}</h2>
    <small>{{ product.created }}</small><br/>
    <p>{{ product.price }} Toman</p>
    <img src="{{ product.image.url }}" style="width: 300px;">
    <p>{{ product.description|safe }}</p><br/><br/>

    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="add to cart">
    </form>
{% endblock %}

products/templates/products/list.html
{% extends 'site/base.html' %}
{% load static %}

{#{% block extra_headers %}#}
{#    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">#}
{#{% endblock %}#}

{% block content %}

    {#    {% for category in categories %}#}

    {#        <div class="btn-group">#}
    {#            <a href="{{ category.get_absolute_url }}" class="btn btn-danger">{{ category.name }}</a>#}
    {#            <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown"#}
    {#                    aria-expanded="false">#}
    {#                <span class="visually-hidden">Toggle Dropdown</span>#}
    {#            </button>#}
    {#            <ul class="dropdown-menu">#}
    {#                {% for sub in category.scategory.all %}#}
    {#                    <li><a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a></li>#}
    {#                {% endfor %}#}
    {#            </ul>#}
    {#        </div>#}

    {#    {% endfor %}#}
    <br/><br/>
    {% for product in product_list %}
        <div class="card" style="width: 18rem; display:inline-block;">
            <img src="{{ product.image.url }}" class="card-img-top">
            <div class="card-body">
                <a href="" class="card-title">{{ product.name }}</a>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

products/templates/products/product_detail_panel.html
{% extends 'panel/base.html' %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-full">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="d-flex align-items-center">
                    <div class="mr-auto">
                        <h3 class="page-title">Product Detail</h3>
                        <div class="d-inline-block align-items-center">
                            <nav>
                                <a href="{% url "products:update" product.slug %}" class="btn btn-warning">Edite</a>
                                <a href="{% url "products:delete" product.slug %}" class="btn btn-danger">Delete</a>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Main content -->
            <section class="content">

                <div class="row">
                    <div class="col-12 col-lg-5 col-xl-4">

                        <div class="box box-inverse bg-img"
                             style="height: 350px; background-image: url({{ product.image.url }});"
                             data-overlay="2">


                            <div class="box-body text-center pb-50">
                                <a href="#">
                                    {#                                    <img class="avatar avatar-xxl avatar-bordered" src="{{ user.profile.image.url }}"#}
                                    {#                                         alt="">#}
                                </a>
                                <h4 class="mt-2 mb-0"><a class="hover-primary text-white"
                                                         href="#">{{ product.name }}</a></h4>
                            </div>


                        </div>


                    </div>
                    <div class="col-12 col-lg-7 col-xl-8">
                        <div class="row">
                            <h3>Product Info</h3>
                            <div class="col-12">
                                <div>
                                    <h3>name:{{ product.name }} <span
                                            class="text-gray pl-10"></span>
                                    </h3>
                                    <h3>description:{{ product.description }} <span
                                            class="text-gray pl-10"></span>
                                    </h3>
                                    <h3>screen_size:{{ product.screen_size }} <span
                                            class="text-gray pl-10"></span>
                                    </h3>
                                    <h3>cpu_cache:{{ product.cpu_cache }} <span
                                            class="text-gray pl-10"></span>
                                    </h3>
                                    <h3>ram:{{ product.ram }} <span
                                            class="text-gray pl-10"></span>
                                    </h3>
                                    <h3>memory_capacity:{{ product.memory_capacity }} <span
                                            class="text-gray pl-10"></span>
                                    </h3>
                                    <h3>battery_description:{{ product.battery_description }} <span
                                            class="text-gray pl-10"></span>
                                    </h3>
                                    <h3>count:{{ product.count }} <span
                                            class="text-gray pl-10"></span>
                                    </h3>


                                </div>
                            </div>
                            {#                                    <a class="form-control btn btn-warning"#}
                            {#                                       href="{% url "profile:update" user.profile.id %}">update profile</a>#}

                        </div>

                    </div>                            <!-- /.tab-content -->
                </div>
                <!-- /.nav-tabs-custom -->
        </div>
    </div>
    <!-- /.row -->

    </section>
    <!-- /.content -->
    </div>
    </div>
{% endblock content %}

products/templates/products/product_list_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

products/templates/products/product_list_panel.html
{% extends 'panel/base.html' %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-full">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="d-flex align-items-center">
                    <div class="mr-auto">
                        <h3 class="page-title">Product List</h3>
                        <div class="d-inline-block align-items-center">
                            <nav>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item active" aria-current="page">
                                        <a class="btn btn-success" href="{% url 'products:create' %}"><h3>Add New
                                            Product</h3></a></li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Main content -->
            <section class="content">

                <div class="row">


                    <div class="col-12">
                        <div class="box">
                            <div class="box-header with-border">
                                <h4 class="box-title">Product List</h4>
                                <div class="box-controls pull-right">
                                    <div class="lookup lookup-circle lookup-right">
                                        <input type="text" name="s">
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-header -->
                            <div class="box-body no-padding">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <tr>
                                            <th>#</th>
                                            <th>name</th>
                                            <th>screen_size</th>
                                            <th>cpu_cache</th>
                                            <th>ram</th>
                                            <th>memory_capacity</th>
                                            <th>count</th>
                                            <th>view</th>
                                        </tr>
                                        {% for product in product_list %}
                                            <tr>
                                                <td>{{ forloop.counter }}</td>
                                                <td>{{ product.name }}</td>
                                                <td>{{ product.screen_size }}</td>
                                                <td>{{ product.cpu_cache }}</td>
                                                <td>{{ product.ram }}</td>
                                                <td>{{ product.memory_capacity }}</td>
                                                <td>{{ product.count }}</td>
                                                <td><a class="btn btn-primary"
                                                       href="{% url "products:detail_admin" product.slug %}">View More</a>
                                                </td>
                                            </tr>
                                        {% empty %}
                                            <h1>No Product Added Net</h1>
                                        {% endfor %}

                                    </table>
                                </div>
                            </div>
                            <!-- /.box-body -->
                        </div>
                        <!-- /.box -->
                    </div>


                </div>
                <!-- /.row -->

            </section>
            <!-- /.content -->
        </div>
    </div>
{% endblock %}

products/templates/products/update.html
{% extends "panel/base.html" %}
{% load widget_tweaks %}
{% block content %}
    <div class="content-wrapper">
        <div class="container-full">
            <div class="content-header">
                <div class="d-flex align-items-center">
                    <div class="mr-auto">
                        <h3 class="page-title text-warning">Product Update {{ product }}</h3>
                    </div>
                </div>
            </div>
            <section class="content">
                <div class="row">
                    <div class="col-12">
                        <div class="box">
                            <div class="box-header with-border">
                                <h4 class="box-title text-warning">Product Form</h4>
                            </div>
                            <div class="box-body">
                                <form method="post" action="" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {% for field in form.visible_fields %}
                                        <label class="col-form-label col-md-2">{{ field.label }}</label>
                                        {{ field|add_class:'form-control' }}
                                        {% for error in field.errors %}
                                            <span class="help-block">{{ error }}</span>
                                        {% endfor %}
                                    {% endfor %}
                                    <br>
                                    <br>
                                    <button type="submit" class="form-control btn btn-warning">
                                        Update Product
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
            </section>
        </div>
    </div>
{% endblock content %}